[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tokengator_minter = "TPLx9nrMKbk3uQoHHL2pxepyYx4A4RH58EAPqsYE9ir"
wen_new_standard = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"

[programs.devnet]
tokengator_minter = "TPLx9nrMKbk3uQoHHL2pxepyYx4A4RH58EAPqsYE9ir"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
# manager account
address = "9SUrE3EPBoXVjNywEDHSJKJdxebs8H8sLgEWdueEvnKX"

[[test.validator.clone]]
address = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"
